services:
  hca:
    image: local/hca
    container_name: hca
    restart: unless-stopped
    ports:
      - 8501:8501
    volumes:
      - /root/hackathon-council-analytics/src/config_sample.toml:/root/.config/hca/config.toml
      - /root/hackathon-council-analytics/CouncilEmbeddings:/app/CouncilEmbeddings
