services:
  hca:
    # image: local/council-analytics:latest
    image: chrisbtt/council-analytics:latest
    container_name: hca
    restart: unless-stopped
    ports:
      - 8501:8501
    volumes:
      - /root/.config/hca/config.toml:/config/config.toml
      - /root/.config/hca/secrets.toml:/config/secrets.toml
