services:
  hca:
    image: local/hca
    container_name: hca
    restart: unless-stopped
    ports:
      - 8052:8080
    volumes:
      - /root/hackathon-council-analytics/src/config_sample.toml:/root/.config/hca/config.toml
