services:
  # Ollama per CPU-Profil
  hca-ollama-cpu:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./src/scripts/ollama_docker_init.sh:/usr/ollama_docker_init.sh
    restart: unless-stopped
    entrypoint: ["/usr/ollama_docker_init.sh"]
    profiles:
      - cpu
      - devel
  # TODO: set entrypoint to load llm & ambedding

  # Ollama per GPU-Profil (NVIDIA)
  hca-ollama-gpu:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu

  hca-app:
    image: local/council-analytics:latest
    # image: chrisbtt/council-analytics:latest
    container_name: hca
    restart: unless-stopped
    ports:
      - 8501:8501
    volumes:
      - /root/.config/hca/config.toml:/config/config.toml
      - /root/.config/hca/secrets.toml:/config/secrets.toml
      - /media/ncdata/__groupfolders/4/TestEmbeddings/:/app/TestEmbeddings/

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    profiles:
      - cpu
      - gpu

volumes:
  ollama:
