# https://realpython.com/python-toml/
[preprocessor]
filestorage = "nextcloud"
fileformat = "txt"

[nextcloud]
folder = "CouncilDocuments"
user = "TeamAgenda"
password = "TeamAgenda@2024"
url = "https://nc-1578619932403564675.nextcloud-ionos.com/remote.php/dav/files/"

[source]
url = "https://www.gemeinderat.heidelberg.de/getfile.asp"
folderPDF = "CouncilDocuments"
folderTXT = "CouncilTexts"
folderEmbeddings = "CouncilEmbeddings"

[model]
embed_name = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
llm_name = "meta-llama/Meta-Llama-3.1-8B-Instruct"
model_dir = "model"

[api]
hf_key = "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"

