[api]
qdrant_url = '<qdrant-url>'
qdrant_api_key = '<api-key-to-huggingface>'
hf_key = "<api-key-to-huggingface>"

[documents.nextcloud]
user = "<user>"
password = "<password>"
url = "https://<path/to/nextcloud.com>/remote.php/dav/files/"
